### ISSUE TITLE
Some postcodes missing since 2023 update

### ISSUE THREAD

**Issue by Michael-Allgoewer-bt** [yetzt/postleitzahlen#3]
I'm afraid something went wrong in the update 2023. Certain postcodes which definitely still exist according to the postcode search of the German post office (https://www.postdirekt.de/plzserver/) are not contained in the data any more, although they were present before. Examples are all postcodes that start with 661, 662, 663, like 66121, 66111, 66115 (all referring to different parts of Saarbrücken). These postcodes are still present in Openstreetmap.

**Comment by yetzt** [comment]
interesting. since i've used osm data via overpass api to generate this dataset, maybe the areas have been tagged wrong. i will investigate and update the dataset when i find the time.

if you want to use the proprietary postcode data from *Deutsche Post*, you may find [this scraper](https://github.com/yetzt/postleitzahlen-scraper) useful.

**Comment by Michael-Allgoewer-bt** [comment]
Thank you! Your scraper link made me notice that one can also find visualized maps as part of the PLZ search https://www.postdirekt.de/plzserver/. I was already using this search, but I hadn't noticed the maps yet... :-) Thank you for that, too!

**Comment by larshei** [comment]
Hey man, thanks for the repo!
Just ran into the same :)

Using this data to display sales results and other business information on a map (as heatmaps etc) and some postcodes missing is not ideal.

If there is anything I can do to help add those, let me know :)

**Comment by yetzt** [comment]
i've imported current data from osm via a new approach, this should resolve the issue of missing data.
