### ISSUE TITLE
Missing attribution in downloadable data

### ISSUE THREAD

**Issue by tobwen** [yetzt/postleitzahlen#4]
### Description
The provided datasets do neither include any indication of the origin of the data nor meet the legal attribution requirements. The data from the OpenStreetMap project and derived products are subject to the Open Database License (ODbL v1.0).

It is important to comply with the following attribution requirements: `OpenStreetMap` plus a link to the ODbL text.
The historical forms of attribution `© OpenStreetMap contributors` or `© OpenStreetMap` are acceptable.

For more information on what is allowed,what is not and what is mandatory, please refer to these websites:
https://osmfoundation.org/wiki/Licence
https://opendatacommons.org/licenses/odbl/

### Polite request
The data has been compiled and maintained by thousands of mappers for over 15 years. Even though the data is freely available, it is not fair game and is subject to copyright. Please respect the work and attribute the origin.

**Comment by yetzt** [comment]
the required copyright notice should be added [here](https://github.com/yetzt/postleitzahlen/blob/main/bin/import.js#L19), i will check if it is indeed missing in the data

**Comment by yetzt** [comment]
it appears, geo2topo drops the property when converting from geojson to topojson. i will add the property in the data and ensure it's present in future releases.

please note that
> The provided datasets do neither include any indication of the origin of the data nor meet the legal attribution requirements. 

is not true, since the attribution was missing from one file due to an oversight, and not from the entire repository. the source of the data has been made abundantly clear using [datapackage](https://datapackage.org/) metadata, and includes a [license document](https://github.com/yetzt/postleitzahlen/blob/main/LICENSE.md) among other indicators. i would advise adjusting your copypaste-template if it does not meet the actual circumstances.

**Comment by tobwen** [comment]
It does not matter under which license the repository is located or whether it is in the README/LICENSE of the repository. If someone uses a hotlink to the release, the user never gets informed about the origin of the data. However, it must be ensured that the attribution to OpenStreetMap is made clear each time the data is presented or redistribute. The license notice must be supplied with the data so that the user gets aware of it.

Others therefore publish an archive (tar, zip, etc.) with the geodata set and an additional data set description with a reference to the origin of the data. However, as you only publish packed geodata sets, the reference must be made in the data set itself.

> i would advise adjusting your copypaste-template if it does not meet the actual circumstances.

I call on you to refrain from making such insinuations. I merely pointed out a mistake that you should know better because of your journalistic work. I could have reported you directly, but I preferred the gentler route of a bug report.
